[package]
name = "splat-cli"
version = "0.50.0"
edition = "2024"
license = "MIT"

[[bin]]
name = "splat"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.42", features = ["derive"] }